# Generated by Django 3.1.7 on 2021-02-25 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.recruiter')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('candidate_source', models.CharField(max_length=200)),
                ('application_received', models.DateField()),
                ('application_status', models.CharField(max_length=200)),
                ('license_status', models.CharField(max_length=200)),
                ('screen_date', models.DateField()),
                ('agreement_sent', models.DateField()),
                ('agreement_signed', models.DateField()),
                ('candidate_notes', models.TextField(blank=True, max_length=500)),
                ('active_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.activestatus')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.recruiter')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.requisition')),
            ],
        ),
    ]
